name: psicodemy
description: "psicodemy."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.4
  geolocator: ^10.1.0
  flutter_local_notifications: ^19.3.0
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/splash_imgs/
    - lib/src/shared_imgs/