name: psicodemy
description: "psicodemy."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.4
  geolocator: ^10.1.0
  flutter_local_notifications: ^19.3.0
  hooks_riverpod: ^3.0.0-dev.16
  flutter_hooks:
  riverpod_annotation: ^3.0.0-dev.16
  freezed_annotation: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0-dev.16
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  freezed: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/splash_imgs/
    - lib/src/shared_imgs/